print("введите 3 названия овоща")
print("первый овощ")
z = input()
print("вторый овощ")
x = input()
print("третий овощ")
c = input()
z1 = z.lower()
x1 = x.lower()
c1 = c.lower()
z2 = z.upper()
x2 = x.upper()
c2 = c.upper()
z3 = z.capitalize()
x3 = x.capitalize()
c3 = c.capitalize()
print(z1,x1,c1)
print(z2,x2,c2)
print(z3,x3,c3)
print("введите количество первого овоща=")
z4 =int(input())
print("введите количество второго овоща=")
x4 =int(input())
print("введите количество третьего овоща=")
c4 =int(input())
print("количество овощей: {0}-{1},{2}-{3},{4}-{5}".format(z,z4,x,x4,c,c4))




